### ISSUE TITLE
Dotted vs Rotz

### ISSUE THREAD

**Issue by HeyItsJono** [volllly/rotz#13]
Hey there, I'm looking for a crossplatform dotfile managing solution, and stumbled across Dotted/Rotz. My main OS is Windows but I have several devices running several different Linux distros. I'm happy to keep using scoop/other package managers to managing installing/uninstalling/updating programs, but I was just wondering if Rotz was ready to use now purely as an alternative to stow for dotfile managing, or if I should use something else in the meantime?

**Comment by volllly** [comment]
Hey, I use also mostly use Rotz on windows at the moment. The latest version I released today is also working on linux (and probably macos but I have not tested that yet ^^).

Using it as a stow alternative should be working 👌 But let me know if you run into any problems or questions. Any feedback is appreciated.

> Right now the following works:
> You can use `rotz clone git@github.com:<user>/<repo>.git` to clone your dotfile repo and `rotz link` to link all dotfiles.
> 
> Here's an example how to setup the repo https://github.com/volllly/.dotfiles (or look at the [not yet perfect docs](https://volllly.github.io/rotz/docs/configuration/dot.yaml))

**Comment by volllly** [comment]
Dotted uses the same config format so you could also use it but for managing the dotfiles the functionality is all in Rotz already (except the for `rotz sync` command which commits and syncs the dotfiles git repo)
