### ISSUE TITLE
Binary in releases

### ISSUE THREAD

**Issue by ADIX7** [volllly/rotz#135]
First of all... Why did I not find this earlier??? Such a great tool! Rust and cross platform, best combo!

I know this project is in its early steps and also only you, @volllly , develop it, so I guess you dont have the time to package it to all platforms. As a temporary solution can you add a step to github actions to build binaries for several platforms? Also add some example one-liner to curl / wget / Invoke-WebRequest them to ~/.bin or something. It would be much easier to not install rust on every computer.

**Comment by volllly** [comment]
Hey, glad you like it 😁

You have a very good point it should be easier to install Rotz.
There is already a draft PR to add binaries to the releases (#98). I just have not yet gotten around to finish it.

The next steps would then be to provide oneliners to install Rotz or small install scripts (like rustup `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` or scoop `irm get.scoop.sh | iex` have).

**Comment by volllly** [comment]
Later I would like to add Rotz to scoop and winget for windows as well as homebrew on macos and im thinking nix, snap or flatpak for linux.

**Comment by volllly** [comment]
@ADIX7 The [latest release](https://github.com/volllly/rotz/releases/tag/v0.9.1) now includes binaries 😁🎉
