### ISSUE TITLE
Better instructions for using defaults

### ISSUE THREAD

**Issue by tomiesz** [volllly/rotz#162]
I've been trying to get defaults to work, but so far i cant seem to get it working the way i would like to. 
My default.toml file is just 
`[linux]
[linux.installs]
cmd: sudo pacman --needed --noconfirm -S {{ name }}`
But how do i actually get a dot for a particular application to use it?
Assuming i just want to install something, without any other actions (no linking etc.) 
Do i just put in an empty file in the respective folder, or do i put something in it?

**Comment by volllly** [comment]
Hey,

yes just putting an empty `vscode/dot.toml` file in the dotfiles repository it should run the command `sudo pacman --needed --noconfirm -S vscode`.

I'll try to clarify that in the docs :)

BTW when using toml you don't need the `[linux]` header just `[linux.installs]` is enough.
