### ISSUE TITLE
Add check on links

### ISSUE THREAD

**Issue by gfriloux** [volllly/rotz#199]
`rotz` is missing a sanity check on `links`.

PEBKAC from your servitor here happened:
I have a file named `config` declared as :
```yaml
links:
  condig:~/.gitconfig
```
As you can see, there is a typo in the name.
`rotz` then created a dead link.

i don't think `rotz` should create deadlinks, it should error, telling the file `condig` does not exists (and optionally, telling me i am stupid :) ).

PS: Thanks for the tool!

**Comment by volllly** [comment]
Hey @gfriloux, thanks alot for reporting :)
I've added checks and a nice error message in the just released [v0.9.3](https://github.com/volllly/rotz/releases/tag/v0.9.3)
